build:
	gcc intercept.c  -I/usr/lib/jvm/java-6-sun/include/ -I/usr/lib/jvm/java-6-sun/include/linux/ -ljvm -L/usr/lib/jvm/java-6-sun/jre/lib/i386/server -L/usr/lib/jvm/java-6-sun/jre/lib/i386/ -o intercept
clean:
	rm -f intercept

