build:
	g++ CTest.cpp -I/usr/lib/jvm/java-6-sun/include/ -I/usr/lib/jvm/java-6-sun/include/linux/ -ljvm -L/usr/lib/jvm/java-6-sun/jre/lib/i386/server -L/usr/lib/jvm/java-6-sun/jre/lib/i386/ -o ctest
clean:
	rm -f a.out ctest

