export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/jvm/java-6-sun/jre/lib/i386/server:/usr/lib/jvm/java-6-sun/jre/lib/i386/

g++ CTest.cpp -I/usr/lib/jvm/java-6-sun/include/ -I/usr/lib/jvm/java-6-sun/include/linux/ -ljvm -L/usr/lib/jvm/java-6-sun/jre/lib/i386/server -L/usr/lib/jvm/java-6-sun/jre/lib/i386/